repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
    -   id: codespell
        exclude: min.js$
- repo: https://github.com/coyainsurance/pre-commit-scalafmt
  rev: 1163a9a9c869a63e74d05937ca61c6e1bb364b87
  hooks:
    - id: scalafmt
- repo: https://github.com/maltzj/google-style-precommit-hook
  rev: b7e9e7fcba4a5aea463e72fe9964c14877bd8130
  hooks:
    - id: google-style-java
-   repo: https://github.com/saily/pre-commit-yapf-isort
    rev: 598ff67cc598dddee43bc611d0bf4a07f4b08619
    hooks:
    -   id: yapf-isort
        exclude: __init__.py
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-eradicate, pep8-naming]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 5.1.1
    hooks:
    -   id: pydocstyle
        exclude: setup.py
-   repo: local
    hooks:
    -   id: scalastyle
        name: scalastyle
        entry: scalastyle -c .scalastyle-config.xml src/main/scala/
        pass_filenames: false
        language: system
    -   id: nginxbeautifier
        name: nginxbeautifier
        entry: nginxbeautifier -s 4
        pass_filenames: true
        language: node
        files: nginx*.conf
