repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
    -   id: codespell
        exclude: min.js$
-   repo: https://github.com/Lucas-C/pre-commit-hooks-java
    rev: 1.3.10
    hooks:
    -   id: validate-html
- repo: https://github.com/coyainsurance/pre-commit-scalafmt
  rev: 1163a9a9c869a63e74d05937ca61c6e1bb364b87
  hooks:
    - id: scalafmt
- repo: https://github.com/maltzj/google-style-precommit-hook
  rev: b7e9e7fcba4a5aea463e72fe9964c14877bd8130
  hooks:
    - id: google-style-java
-   repo: local
    hooks:
    -   id: scalastyle
        name: scalastyle
        entry: scalastyle -c .scalastyle-config.xml src/main/scala/
        pass_filenames: false
        language: system
    -   id: nginxbeautifier
        name: nginxbeautifier
        entry: nginxbeautifier -s 4
        pass_filenames: true
        language: node
        files: .*nginx.*
