- hosts: localhost

  vars:
    project_root: ../../
    sbt_js_bundle_folder: js/target/scala-2.13/scalajs-bundler/main/
    scala_resources_folder: jvm/src/main/resources/
    nginx_srv_static_folder: /srv/ryw-web/static/

  tasks:
    - name: "Build JS webpack bundle"
      command: sbt 'rywJS/fullOptJS::webpack'
      args:
        chdir: "{{ project_root }}"
    - name: "Copy webpack JS to Scala sources folder"
      copy:
        src: "{{ project_root }}/{{ sbt_js_bundle_folder }}/ryw-web-opt-bundle.js"
        dest: "{{ project_root }}/{{ scala_resources_folder}}/ryw-web-opt-bundle.js"
    - name: "Copy JS to local Nginx static assets folder"
      become: yes
      copy:
        src: "{{ item }}"
        dest: "{{ nginx_srv_static_folder }}"
        owner: nginx
        group: nginx
      loop:
        - "{{ project_root }}/{{ sbt_js_bundle_folder }}/ryw-web-opt-bundle.js"
        - "{{ project_root }}/{{ sbt_js_bundle_folder }}/ryw-web-opt-bundle.js.map"
        - "{{ project_root }}/{{ scala_resources_folder }}/ryw.js"

- hosts: ryw

  vars:
    project_root: ../../
    sbt_js_bundle_folder: js/target/scala-2.13/scalajs-bundler/main/
    scala_resources_folder: jvm/src/main/resources/
    nginx_srv_static_folder: /var/www/html/static/
    no_remote: "{{ lookup('env', 'NO_REMOTE') }}"

  become: yes

  tasks:
    - name: "Copy JS to remote Nginx static assets folder"
      when: no_remote | length == 0
      copy:
        src: "{{ item }}"
        dest: "{{ nginx_srv_static_folder }}"
        owner: www-data
        group: www-data
      loop:
        - "{{ project_root }}/{{ sbt_js_bundle_folder }}/ryw-web-opt-bundle.js"
        - "{{ project_root }}/{{ sbt_js_bundle_folder }}/ryw-web-opt-bundle.js.map"
        - "{{ project_root }}/{{ scala_resources_folder }}/ryw.js"
