- hosts: ryw

  vars:
    no_remote: "{{ lookup('env', 'NO_REMOTE') }}"

  become: yes

  tasks:
  - name: Restart systemd service
    when: no_remote | length == 0
    systemd:
      name: ryw-web.service
      state: restarted
