- hosts: localhost

  vars:
    project_root: ../../
    sbt_jar_folder: jvm/target/scala-2.13/

  tasks:
    - name: "Build web server .jar"
      command: sbt 'rywJVM/assembly'
      args:
        chdir: "{{ project_root }}"

    - name: Get all .jar files
      find:
        paths: "{{ project_root }}/{{ sbt_jar_folder }}"
        patterns: '*.jar'
      register: found_files

    - name: Get latest .jar
      set_fact:
        latest_jar: "{{ found_files.files | sort(attribute='mtime',reverse=true) | first }}"

- hosts: ryw

  vars:
    remote_jar_dest: /usr/local/bin/ryw-web.jar

  become: yes

  tasks:
    - name: "Copy .jar to remote"
      copy:
        src: "{{ hostvars['localhost']['latest_jar']['path'] }}"
        dest: "{{ remote_jar_dest }}"
